### ISSUE TITLE
Xcode 7.2 (7C68)

### ISSUE THREAD

**Issue by freefelt** [ThilinaHewagama/HCTAutoFolding#2]
Does not work (or install). Tried to Install within Alcatraz too. It just does not work at all.

**Comment by carbamide** [comment]
Same here.

**Comment by carbamide** [comment]
Any debugging info that I could provide that would be of assistance?

**Comment by ForrestAlfred** [comment]
+ 1

**Comment by oit63** [comment]
Now it works perfectly on 7.2(7C68), thanks for your effort !
